### ISSUE TITLE
Provide an abstraction layer for the DataSource/DataWriter

### ISSUE THREAD

**Issue by grahl** [spress/Spress#100]
Hi

I wanted to figure out where I had used which tags in my posts and ideally directly alter them (harmonize, merge, etc.). I started with a command plugin and did get there but not with two rather ugly workarounds, one being calling site:build fully and second saving the results for processing in a  global variable. See here: https://github.com/grahl/spress-tag-manager

Ideally, I'd like to call something in my command plugin which provides me with something akin to a database abstraction layer so that I could modify the underlying data as needed without thinking about rendering or anything else. Is there an undocumented way to do this or is this something which could be put on the roadmap for the next release?

Thanks!

**Comment by yosymfony** [comment]
Hi @grahl. I just reviewed your tag-manager plugin and I tell you that the [global variable is not necessary](https://github.com/grahl/spress-tag-manager/blob/master/GrahlSpressTagManager.php#L48) because your plugin and the event-handler function are in the same context. In other words, you only need to declare a class variable.

Details about how read and write items from a command plugin can be found below (if you are working on a regular plugin, you have available another [interface to get access to this objects](http://spress.yosymfony.com/docs/developers/events-list/#environmentevent)):

**How to read items?**
You need to use the [DataSourceManager](https://github.com/spress/Spress-core/blob/master/DataSource/DataSourceManager.php) class ([docs here](http://spress.yosymfony.com/docs/developers/data-sources/)):

```php
use Yosymfony\Spress\Core\Spress;

$spress = new Spress();
$spress['spress.config.site_dir'] = '/path-to-your-spress-site';

$dataSourceManager = $spress['spress.dataSourceManager'];
$dataSourceManager->load(); // loads items (items, layouts and includes)

$items = $dataSourceManager->getItems(); // posts, pages... etc
```

**Access to the Data-writer:**
You can access to the prebuild data-writer by `$spress['spress.dataWriter']` key; This one point to the site build folder. If you need to work with another location, you need to build your own instance.

```php
$dataWriter = $spress['spress.dataWriter'];
$dataWriter->write($item); // Writes an item into the output folder.
```

**How to build your own data-writer instance?**
(all data-writers follow the [DataWriterInterface](https://github.com/spress/Spress-core/blob/master/DataWriter/DataWriterInterface.php). [You can found more datails here](http://spress.yosymfony.com/docs/developers/data-writer/).)

```php
use Symfony\Component\Filesystem\Filesystem;
use Yosymfony\Spress\Core\DataWriter\FilesystemDataWriter;

$dataWriter = new FilesystemDataWriter(new Filesystem (), '/your-path');
```

**Comment by grahl** [comment]
Hi @yosymfony 

Thanks so much for your detailed response!

I now used a private static variable to solve this since a regular class variable doesn't work since it isn't the same class instance on execution and on the event.

In the next iteration I'll follow your example and instantiate the dataSourceManager directly, it felt a bit weird to me since I expected that I must be doing something wrong if my module is determining the site base directory and not getting this from Spress itself.

**Comment by yosymfony** [comment]
@grahl yes, it weird. I'm going to see what can I do for the Spress 2.2
